function export_a2_report(metrics, profileSummary, crosscheck, ...
    circularSignificance, safetyEnvelope, ceilingEstimate, harmonicFit, ...
    outputDirectory)
%EXPORT_A2_REPORT Write machine-readable tables and concise decision text.

arguments
    metrics table
    profileSummary table
    crosscheck table
    circularSignificance table
    safetyEnvelope table
    ceilingEstimate struct
    harmonicFit struct
    outputDirectory (1,1) string
end

if ~isfolder(outputDirectory)
    mkdir(outputDirectory);
end

writetable(metrics, fullfile(outputDirectory, "matlab-run-metrics.csv"));
writetable(profileSummary, ...
    fullfile(outputDirectory, "matlab-profile-summary.csv"));
writetable(crosscheck, ...
    fullfile(outputDirectory, "matlab-crosscheck.csv"));
writetable(circularSignificance, ...
    fullfile(outputDirectory, "matlab-circular-significance.csv"));
writetable(safetyEnvelope, ...
    fullfile(outputDirectory, "matlab-safety-envelope.csv"));
writetable(harmonicFit.PerLevel, ...
    fullfile(outputDirectory, "matlab-harmonic-fit.csv"));
save(fullfile(outputDirectory, "matlab-analysis.mat"), "metrics", ...
    "profileSummary", "crosscheck", "circularSignificance", ...
    "safetyEnvelope", "ceilingEstimate", "harmonicFit");

reportPath = fullfile(outputDirectory, "matlab-decision.txt");
fid = fopen(reportPath, "wt", "n", "UTF-8");
if fid < 0
    error("A2Analysis:ReportOpen", "Cannot create report: %s", reportPath);
end
cleanup = onCleanup(@() fclose(fid));

fprintf(fid, "MATLAB A2-family offline analysis\n");
fprintf(fid, "Generated: %s\n", string(datetime("now", ...
    TimeZone="Asia/Ho_Chi_Minh", Format="yyyy-MM-dd HH:mm:ss Z")));
fprintf(fid, "Cross-check: %d/%d metrics match PowerShell\n\n", ...
    sum(crosscheck.MetricMatch), height(crosscheck));

for index = 1:height(profileSummary)
    row = profileSummary(index,:);
    format = ['%s\n  power=%.1f%% runs=%d pass=%d fault=%d moved=%d\n' ...
        '  maxStep=%g raw maxTravel=%.4f deg\n' ...
        '  settledRange=%.4f deg R=%.4f candidate=%d cluster1deg=%d\n\n'];
    fprintf(fid, format, char(row.Profile), row.PowerPercent, ...
        row.TotalRuns, row.HardPassRuns, ...
        row.FaultRuns, row.MovedRuns, row.MaxAbsStepRaw, ...
        row.MaxAbsTravelDeg, row.SettledRangeDeg, row.SettledResultantR, ...
        row.PowerEnvelopeCandidate, row.WithinOneDegCluster);
end

fprintf(fid, "Circular significance (is SettledModuloRaw distinguishable from uniform?):\n");
for index = 1:height(circularSignificance)
    row = circularSignificance(index,:);
    fprintf(fid, "  %s: power=%.1f%% n=%d R=%.4f Rayleigh p=%.4f bootstrap95%%CI=[%.4f, %.4f]\n", ...
        char(row.Profile), row.PowerPercent, row.SampleCount, row.ResultantR, ...
        row.RayleighP, row.BootstrapCILow, row.BootstrapCIHigh);
end
fprintf(fid, ['  p<0.05 rejects "uniform/no phase-lock" at that power level.\n' ...
    '  A wide bootstrap CI means the R point estimate is not trustworthy yet\n' ...
    '  at n=5 -- do not over-read a single power level''s R without it.\n\n']);

fprintf(fid, "Safety envelope (includes hard-gate FAULT runs, not just passes):\n");
for index = 1:height(safetyEnvelope)
    row = safetyEnvelope(index,:);
    fprintf(fid, "  %s: power=%.1f%% runs=%d faults=%d [%s]\n", ...
        char(row.Profile), row.PowerPercent, row.TotalRuns, row.FaultRuns, ...
        char(row.FaultKinds));
    fprintf(fid, "    maxStep=%g/45 raw (%.0f%%) maxTravel=%.3f/%.3f deg (%.0f%%)\n", ...
        row.MaxStepRawAny, row.StepBudgetFraction*100, row.MaxTravelDegAny, ...
        910.0*360.0/65536.0, row.TravelBudgetFraction*100);
end
fprintf(fid, ['  Linear-extrapolated ceiling (diagnostic only, NOT a validated\n' ...
    '  safe limit -- confirm empirically one power step at a time):\n' ...
    '    step budget crosses 45 raw at approximately %.2f%% power\n' ...
    '    travel budget crosses 910 raw at approximately %.2f%% power\n\n'], ...
    ceilingEstimate.StepCeilingPercent, ceilingEstimate.TravelCeilingPercent);

fprintf(fid, "Restoring-torque harmonic fit (FinalTravelRaw ~ a*sin(theta)+b*cos(theta)+c):\n");
for index = 1:height(harmonicFit.PerLevel)
    row = harmonicFit.PerLevel(index,:);
    fprintf(fid, "  %s: power=%.1f%% n=%d amplitude=%.2f raw phase=%.1f raw (%.2f deg) R2=%.4f p=%.6f\n", ...
        char(row.Profile), row.PowerPercent, row.N, row.AmplitudeRaw, ...
        row.PhaseRaw, row.PhaseDeg, row.RSquared, row.PValue);
end
fprintf(fid, "  Pooled (all safe runs, all power levels): n=%d amplitude=%.2f raw phase=%.1f raw (%.2f deg) R2=%.4f p=%.6f\n", ...
    harmonicFit.Pooled.N, harmonicFit.Pooled.AmplitudeRaw, ...
    harmonicFit.Pooled.PhaseRaw, harmonicFit.Pooled.PhaseDeg, ...
    harmonicFit.Pooled.RSquared, harmonicFit.Pooled.PValue);
fprintf(fid, ['  p<0.05 rejects "no phase dependence" -- a significant fit''s phase\n' ...
    '  is a candidate A3 offset. Per-level amplitude trend vs power is a second,\n' ...
    '  independent read on whether higher power is producing more restoring\n' ...
    '  torque. Requires GatePass runs only; fault runs are excluded because\n' ...
    '  their travel reflects a safety cutoff, not a settled position.\n\n']);

fprintf(fid, ['Interpretation rules:\n' ...
    '- PowerEnvelopeCandidate means >=5 included runs were all safe and all\n' ...
    '  moved >0.1 deg, matching the docs/control-a2-alignment-hardware-test.md\n' ...
    '  "5/5 run" gate. Fewer than 5 runs can never set this true.\n' ...
    '- PowerEnvelopeCandidate is a necessary, not sufficient, condition for the\n' ...
    '  official gate: it does not check PrimeStateValid/EnableStateValid/\n' ...
    '  EnablePowerPpm or zero-fault health counters. Confirm those from the\n' ...
    '  summary CSV directly before treating a profile as gate-passed.\n' ...
    '- WithinOneDegCluster is diagnostic only, not an official acceptance gate.\n' ...
    '- MATLAB never authorizes a higher hardware power after a hard-gate fault.\n' ...
    '- The power-ceiling estimate is a straight-line fit through a handful of\n' ...
    '  power levels, not a physical model; a level that already faulted (see\n' ...
    '  FaultKinds above) is the real ceiling evidence, not the extrapolation.\n']);
end
